language: ruby
rvm:
  - 2.6.3

before_install:
- export TZ=Europe/Zürich

before_script:
 - chmod +x ./_scripts/cibuild

script: ./_scripts/cibuild

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler

notifications:
  email: true
