language: ruby
rvm:
  - 2.6.3

install: gem install jekyll html-proofer
script: jekyll build && htmlproofer ./_site

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler

notifications:
  email: true