theme: jekyll-theme-slate
permalink: /:categories/:title
url: https://gymnewsium.ch
paginate: 10
paginate_path: "/archiv/page:num/"
plugins:
  - jekyll-paginate
  - jekyll-last-modified
exclude: [vendor]
title: gymNEWSium
description: Eine monatliche Gymerzeitung
copyright: 2021 Verein gymNEWSium, Burgdorf
categorylist:
  announcements: 
    title: Ankündigungen
    url: /announcements/
  releases:
    title: Ausgaben
    url: /ausgaben/