theme: jekyll-theme-slate
permalink: /:categories/:title
url: https://gymnewsium.ch
paginate: 10
paginate_path: "/archiv/page:num/"
plugins:
  - jekyll-paginate
  - jekyll-last-modified
exclude: [vendor]
title: gymNEWSium
description: Eine unabhängige Gymerzeitung aus Burgdorf
copyright: 2021 Verein gymNEWSium, Burgdorf
categorylist:
  announcements: 
    title: Ankündigungen
    url: /announcements/
  articles:
    title: Artikel
    url: /articles/
  releases:
    title: Ausgaben
    url: /releases/
taglist:
  aktuelles:
    title: Aktuelles
    url: /tag/aktuelles/
  allgemeinwissen:
    title: Allgemeinwissen
    url: /tag/allgemeinwissen/
  geschichte:
    title: Geschichte
    url: /tag/geschichte/
  gymerleben:
    title: Gymerleben
    url: /tag/gymerleben/
  politik:
    title: Politik
    url: /tag/politik/
defaults:
  -
    scope:
      path: "modules"
    values:
      sitemap: false
