theme: jekyll-theme-slate
permalink: /:categories/:title/
url: https://gymnewsium.ch
# paginate: 10
# paginate_path: "/archiv/page:num/"
plugins:
  # - jekyll-paginate
  - jekyll-last-modified
page_excerpts: true
enable_subposts: true
exclude: [vendor, README.md, README-gh-pages.md, LICENSE, Gemfile, Gemfile.lock, CNAME]
title: gymNEWSium
description: Eine unabhängige Gymerzeitung aus Burgdorf
copyright: 2021 Verein gymNEWSium, Burgdorf
categorylist:
  announcements: 
    title: Ankündigungen
    singulartitle: Ankündigung
    url: /announcements/
  articles:
    title: Artikel
    singulartitle: Artikel
    url: /articles/
  releases:
    title: Ausgaben
    singulartitle: Ausgabe
    url: /releases/
taglist:
  aktuelles:
    title: Aktuelles
    url: /tag/aktuelles/
    bg: |-
      #ee9c00
  allgemeinwissen:
    title: Allgemeinwissen
    url: /tag/allgemeinwissen/
    bg: |-
      #0b0
  gymerleben:
    title: Gymerleben
    url: /tag/gymerleben/
    bg: |-
      #00b7ff
  politik:
    title: Politik
    url: /tag/politik/
    bg: |-
      #c00
defaults:
  - 
    scope: 
      path: ""
      type: "posts"
    values:
      excerpt_separator: "<!--more-->"
      searchable: true
  -
    scope:
      path: "modules"
    values:
      sitemap: false
  -
    scope:
      path: "pages"
    values:
      searchable: true
