theme: jekyll-theme-slate
permalink: /:categories/:title
url: https://gymnewsium.ch
paginate: 10
paginate_path: "/archiv/page:num/"
plugins:
  - jekyll-paginate
  - jekyll-last-modified
exclude: [vendor]
title: gymNEWSium
description: Die Gymerzeitung aus Burgdorf