theme: jekyll-theme-slate
permalink: /:categories/:title/
url: https://gymnewsium.ch
# paginate: 10
# paginate_path: "/archiv/page:num/"
plugins:
  # - jekyll-paginate
  - jekyll-last-modified
page_excerpts: true
enable_subposts: true
google_site_verification: AXsYv8VFf-r-4a-bUfFDbfO2KgBhhvKMDm2QtjmQ72Y
exclude: [vendor, README.md, README-gh-pages.md, LICENSE, Gemfile, Gemfile.lock, CNAME]
title: gymNEWSium
description: Eine unabhängige Gymerzeitung aus Burgdorf
copyright: 2022 gymNEWSium, Burgdorf
categorylist:
  announcements: 
    title: Ankündigungen
    singulartitle: Ankündigung
    url: /announcements/
  articles:
    title: Artikel
    singulartitle: Artikel
    url: /articles/
  galerien:
    title: Galerien
    singulartitle: Galerie
    url: /galerien/
  kolumnen:
    title: Kolumnen
    singulartitle: Kolumne
    url: /kolumnen/
  releases:
    title: Ausgaben
    singulartitle: Ausgabe
    url: /releases/
taglist:
  aktuelles:
    title: Aktuelles
    url: /tag/aktuelles/
    bg: |-
      #ee9c00
  allgemeinwissen:
    title: Allgemeinwissen
    url: /tag/allgemeinwissen/
    bg: |-
      #0b0
  gymerleben:
    title: Gymerleben
    url: /tag/gymerleben/
    bg: |-
      #00b7ff
  politik:
    title: Politik
    url: /tag/politik/
    bg: |-
      #c00
defaults:
  - 
    scope: 
      path: ""
      type: "posts"
    values:
      excerpt_separator: "<!--more-->"
      searchable: true
  -
    scope:
      path: "modules"
    values:
      sitemap: false
  -
    scope:
      path: "pages"
    values:
      searchable: true
  -
    scope:
      path: "_posts/kolumnen"
    values:
      authorurl: mailto:gymnewsium@tpto.ch?subject=%5BKolumnen%5D%20Kontaktanfrage
      defaultalerts:
        - 
          type: warning
          title: Hinweis
          text: |-
              Dies ist eine Kolumne. Kolumnen werden nicht von der gymNEWSium Redaktion geschrieben und wir übernehmen keine Verantwortung für deren Inhalt. Mehr Informationen über Kolumnen befinden sich <a class="alert-link text-decoration-underline" href="/kolumnen/info/">hier</a>.
  -
    scope:
      path: "_posts/galerien"
    values:
      readbuttontext: "Galerie ansehen"
      defaultalerts:
        - 
          type: success
          title: Hinweis
          text: |-
              E-Mail für Anfragen zur Entfernung und Einreichen von zusätzlichen Bildern:
              <a href="mailto:gymnewsium@tpto.ch">gymnewsium@tpto.ch</a>
